# Coleta logs de TODOS os containers (inclui app-java-lab)
filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
      - add_fields:
          target: lab
          fields:
            scenario: "observabilidade"

# Carrega dashboards (opcional) e garante que o setup fala com o Kibana interno
setup.kibana:
  host: "kibana:5601"

# Saída para o ES interno do compose (porta interna 9200)
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: "http"

# Log um pouco mais verboso enquanto valida (pode voltar para info depois)
logging.level: warning
